config/routes.rb
Rails.application.routes.draw do
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'log_in', to: 'sessions#new', as: 'log_in' 
  get 'sign_up' , to: 'users#new', as: 'sign_up'
 
  resources :users do
    get :change_permission, on: :member
  end
  
  resources :sessions
  get 'users/new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  get 'auth/vkontakte/callback', to: 'omniauth#create'
  get 'auth/facebook/callback', to: 'omniauth#create'

  namespace :admin do
    root 'users#index'
    resources :users, only: [:index, :destroy]
    resources :videos
    resources :films
    resources :cartoons
  end

  resources :videos do
     member do
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
    end
    get :favourite, on: :member
    get '/videos', to: 'pages#video'
  end

  resources :films do
    resources :comments
    member do
      put "like", to: "films#upvote"
      put "dislike", to: "films#downvote"
    end
    get '/films', to: 'pages#film'
  end

  resources :cartoons do
    member do
      put "like", to: "cartoons#upvote"
      put "dislike", to: "cartoons#downvote"
    end
    get '/cartoons', to: 'pages#cartoon'
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartoon.rb
class Cartoon < ApplicationRecord
	belongs_to :user
  acts_as_votable
	self.per_page = 4
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :films
	has_many :films
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :film
end

app/models/favourite_video.rb
class FavouriteVideo < ApplicationRecord
  belongs_to :user
  belongs_to :video

  def self.manage(video)
    object = find_by(video: video)
    object ? object.destroy : create(video: video)
  end
end

app/models/film.rb
class Film < ApplicationRecord
  dragonfly_accessor :imagefilm
  dragonfly_accessor :screenshotsactors
  has_and_belongs_to_many :categories
  belongs_to :category

  acts_as_votable
  has_many :comments

  self.per_page = 5
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  attr_accessor :password
  before_save :encrypt_password
  has_many :account, dependent: :destroy
  has_many :favourite_videos

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  acts_as_votable
  has_many :favourite_videos

  self.per_page = 4

	

end

app/controllers/admins_controller.rb
class AdminsController < ActionController::Base
  layout 'admin/application'

  before_action :require_admin

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def authorize
    redirect_to log_in_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
	def index
    @films = Film.all.page(params[:page]).where("name LIKE ?", "%#{params[:search]}%")
  end

  def show
  	@film = Film.find(params[:id])
  end

  def upvote 
    @film = Film.find(params[:id])
    @film.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @film = Film.find(params[:id])
    @film.downvote_by current_user
    redirect_to :back
  end

  private

  def film_params 
    params.require(:film).permit(:name, :quality, :genre, :year, :country, :duration, :producer, :premiere, :transfer, :image_film, :description, :screenshots_and_actors, :link, :treilerlink, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_resourse, only: [:show, :edit, :update, :change_permission]

  def index
    @users = User.all
  end
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def change_permission
    @user.update(admin: !@user.admin)
    redirect_to :back
  end


  private
 
    def current_resourse
      @user = User.find(params[:id])
    end

    def set_user
      @user = current_user
    end
    
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartoons_helper.rb
module CartoonsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper

  def favourite_video(video)
    if current_user && current_user.favourite_videos.map(&:video).include?(video)
    'text-danger'
    else
    'text-muted'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie</title>
    <%= stylesheet_link_tag    'admin_application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class = "container">
      <br>
      <%= render 'shared/admin/headers' %>
      <br>
      <div class="well">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_content.html.erb
<div class="box_1">
  <h1 class="m_2">Most Popular videos</h1>
  <br>
  <div class="clearfix"> </div>
</div>
<div class="row">
  <div class="col-md-6">
    <iframe width="100%" height="305" src="https://www.youtube.com/embed/2he_g589hgw" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="col-md-6">
    <iframe width="100%" height="305" src="https://www.youtube.com/embed/Ys3mXt3WqMA" frameborder="0" allowfullscreen></iframe>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-6">
    <iframe width="100%" height="305" src="https://www.youtube.com/embed/2oEDX40ME_Q" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="col-md-6">
    <iframe width="100%" height="305" src="https://www.youtube.com/embed/94G-0L3PKcs" frameborder="0" allowfullscreen></iframe>
  </div>
</div>
<br>
  <center><button class="buttons"><%= link_to "More video", videos_path %></button></center>
  

app/views/shared/_footer.html.erb
<footer id="footer">
  <div id="footer-3d">
    <div class="gp-container">
      <span class="first-widget-bend"></span>
    </div>    
  </div>
  <div id="footer-widgets" class="gp-footer-larger-first-col">
    <div class="gp-container">
      <div class="footer-widget footer-1">
        <div class="wpb_wrapper">
          <%= link_to root_path do %>
            <%= image_tag "f_logo.png" %>
          <% end %>
        </div> 
        <br>
          <p>Movies Site is provided for movies. Also to write comments and reviews evaluation movie site users.</p>
          <p class="text">As well as the possible purchase of any film genre</p>
      </div>
      <div class="footer_box">
        <div class="col_1_of_3 span_1_of_3">
          <h3>Categories</h3>
          <ul class="first">
            <li><a href="#">Films</a></li>
            <li><a href="#">Serials</a></li>
            <li><a href="#">Audio</a></li>
          </ul>
        </div>
        <div class="col_1_of_3 span_1_of_3">
          <h3>Information</h3>
          <ul class="first">
            <% if current_admin %>
                <li><%= link_to "Admin",  admin_root_path %></li>
              <% else %>
                <li><%= link_to "My Profile", current_user %></p></li>
            <% end %>
            <li><a href="#">Settings Account</a></li>
            <li><a href="#">About</a></li>
          </ul>
        </div>
        <div class="col_1_of_3 span_1_of_3">
          <h3>Follow Us</h3>
          <ul class="first">
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Youtube</a></li>
          </ul>
          <div class="copy">
            <p>&copy; 2015 Movie </a></p>
          </div>
        </div>
        <div class="clearfix"> </div>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="header_top">
  <div class="col-sm-3 logo">
    <%= link_to root_path do %>
      <%= image_tag "logo.png" %>
    <% end %>
  </div>
  <div class="col-sm-6 nav">
    <ul>
     <li> <span class="simptip-position-bottom simptip-movable" data-tooltip="Serials"><a href="#"> </a></span></li>
     <li><span class="simptip-position-bottom simptip-movable" data-tooltip="Films"><%= link_to films_path do %><% end %> </span></li>
     <li><span class="simptip-position-bottom simptip-movable" data-tooltip="Video"><%= link_to videos_path do %><% end %></span></li>
     <li><span class="simptip-position-bottom simptip-movable" data-tooltip="Audio"><a href="#"> </a></span></li>
     <li><span class="simptip-position-bottom simptip-movable" data-tooltip="Cartoon"><%= link_to cartoons_path do %><% end %></span></li>
     <li><span class="simptip-position-bottom simptip-movable" data-tooltip="About"><a href="#"> </a></span></li>
   </ul>
  </div>
  <div class="col-sm-3 header_right">
    <ul class="header_right_box">
      <% if current_user %>
        <li><p><%= image_tag current_user.avatar_url(:thumb), class: "img-circle" %></p></li>
        <li><p><%= link_to current_user.firstname, current_user, class: "registaration"  %></p></li>
        <li><p><%= link_to log_out_path, class: "registaration"  do %><span><i class="fa fa-sign-out"></i></span><% end %></p></li>
      <% else %>
        <li><p><%= link_to "My Profile", log_in_path, class: "registaration" %></p></li>
      <% end %> 
      <div class="clearfix"> </div>
    </ul>
  </div>
  <div class="clearfix"> </div>
</div>

app/views/shared/_slider.html.erb
<script>
  $(function () {
    $("#slider").responsiveSlides({
      auto: true,
      nav: true,
      speed: 500,
      namespace: "callbacks",
      pager: true,
    });
  });
</script>
  <div class="callbacks_container">
    <ul class="rslides" id="slider">
      <li><%= image_tag "banner.jpg", class: "img-responsive"  %>
        <div class="button">
          <a href="#" class="hvr-shutter-out-horizontal">Watch Now</a>
        </div>
      </li>
      <li><%= image_tag "banner1.jpg", class: "img-responsive"  %>
        <div class="button">
          <a href="#" class="hvr-shutter-out-horizontal">Watch Now</a>
        </div>
      </li>
      <li><%= image_tag "banner2.jpg", class: "img-responsive"  %>
        <div class="button">
          <a href="#" class="hvr-shutter-out-horizontal">Watch Now</a>
        </div>
      </li>
    </ul>
  </div>
  <div class="banner_desc">
    <div class="col-md-9">
      <ul class="list_1">
        <li>Published <span class="m_1">Feb 20, 2016</span></li>
        <li>Updated <span class="m_1">Feb 20 2016</span></li>
        <li>Rating <span class="m_1"><%= image_tag "rating.png" %></span></li>
      </ul>
    </div>
    <div class="col-md-3 grid_1">
      <ul class="list_1 list_2">
        <li><i class="icon1"> </i><p>2,548</p></li>
        <li><i class="icon2"> </i><p>215</p></li>
        <li><i class="icon3"> </i><p>546</p></li>
      </ul>
    </div>
  </div>