config/routes.rb
Rails.application.routes.draw do
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'log_in', to: 'sessions#new', as: 'log_in' 
  get 'sign_up' , to: 'users#new', as: 'sign_up'
 
  resources :users do
    get :change_permission, on: :member
  end
  
  resources :sessions
  get 'users/new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  get 'auth/vkontakte/callback', to: 'omniauth#create'
  get 'auth/facebook/callback', to: 'omniauth#create'

  namespace :admin do
    root 'users#index'
    resources :users, only: [:index, :destroy]
    resources :videos
    resources :films
    resources :cartoons
  end

  resources :videos do
     member do
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
    end
    get :favourite, on: :member
    get '/videos', to: 'pages#video'
  end

  resources :films do
    resources :comments
    member do
      put "like", to: "films#upvote"
      put "dislike", to: "films#downvote"
    end
    get '/films', to: 'pages#film'
  end

  resources :cartoons do
    member do
      put "like", to: "cartoons#upvote"
      put "dislike", to: "cartoons#downvote"
    end
    get '/cartoons', to: 'pages#cartoon'
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartoon.rb
class Cartoon < ApplicationRecord
	belongs_to :user
  acts_as_votable
	self.per_page = 4
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :films
	has_many :films
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :film
end

app/models/favourite_video.rb
class FavouriteVideo < ApplicationRecord
  belongs_to :user
  belongs_to :video

  def self.manage(video)
    object = find_by(video: video)
    object ? object.destroy : create(video: video)
  end
end

app/models/film.rb
class Film < ApplicationRecord
  dragonfly_accessor :imagefilm
  dragonfly_accessor :screenshotsactors
  has_and_belongs_to_many :categories
  belongs_to :category

  acts_as_votable
  has_many :comments

  self.per_page = 5
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  attr_accessor :password
  before_save :encrypt_password
  has_many :account, dependent: :destroy
  has_many :favourite_videos

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  acts_as_votable
  has_many :favourite_videos

  self.per_page = 4

	

end

app/controllers/admin/films_controller.rb
class Admin::FilmsController < AdminsController
  before_action :authorize, only: [:index, :destroy, :new]
  before_action :require_admin, only: [:index, :destroy, :new]
  before_action :current_film, only: [:show, :edit, :update, :destroy]

  def index
    @films = Film.all.where("name LIKE ?", "%#{params[:search]}%")
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.create(film_params)
    if @film.save
      redirect_to admin_films_path 
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @film.update(film_params)
      redirect_to admin_films_path 
    else
      render 'edit'
    end
  end

  def destroy
    @film.destroy
    redirect_to admin_films_path 
  end


  private

  def film_params 
    params.require(:film).permit(:name, :quality, :genre, :year, :country, :duration, :producer, :premiere, :transfer, :image_film, :description, :screenshots_and_actors, :link, :treilerlink, category_ids: [])
  end

  def current_film
    @film = Film.find(params[:id])
  end

  def require_admin
    redirect_to root_path unless current_user.try(:admin?)
    flash[:success] = "You admin?"
  end
end

app/controllers/admins_controller.rb
class AdminsController < ActionController::Base
  layout 'admin/application'

  before_action :require_admin

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def authorize
    redirect_to log_in_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/cartoons_controller.rb
class CartoonsController < ApplicationController
    
  def index
    @cartoons = Cartoon.all.page(params[:page]).where("name LIKE ?", "%#{params[:search]}%") 
  end

  def upvote 
    @cartoon = Cartoon.find(params[:id])
    @cartoon.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @cartoon = Cartoon.find(params[:id])
    @cartoon.downvote_by current_user
    redirect_to :back
  end

  private


  def cartoon_params
    params.require(:cartoon).permit(:name)
  end
end

app/controllers/concerns/films_controller.rb
class FilmsController < ApplicationController

	def index
		@films = Film.all
	end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
	def index
    @films = Film.all.page(params[:page]).where("name LIKE ?", "%#{params[:search]}%")
  end

  def show
  	@film = Film.find(params[:id])
  end

  def upvote 
    @film = Film.find(params[:id])
    @film.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @film = Film.find(params[:id])
    @film.downvote_by current_user
    redirect_to :back
  end

  private

  def film_params 
    params.require(:film).permit(:name, :quality, :genre, :year, :country, :duration, :producer, :premiere, :transfer, :image_film, :description, :screenshots_and_actors, :link, :treilerlink, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_resourse, only: [:show, :edit, :update, :change_permission]

  def index
    @users = User.all
  end
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def change_permission
    @user.update(admin: !@user.admin)
    redirect_to :back
  end


  private
 
    def current_resourse
      @user = User.find(params[:id])
    end

    def set_user
      @user = current_user
    end
    
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :avatar)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :current_video, only: [:favourite]
    
  def index
    @videos = Video.all.page(params[:page]).where("name LIKE ?", "%#{params[:search]}%")
    
  end

  def favourite
    current_user.favourite_videos.manage(@video)
  end

  def upvote 
    @video = Video.find(params[:id])
    @video.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @video = Video.find(params[:id])
    @video.downvote_by current_user
    redirect_to :back
  end

  private

  def current_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:name)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartoons_helper.rb
module CartoonsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper

  def favourite_video(video)
    if current_user && current_user.favourite_videos.map(&:video).include?(video)
    'text-danger'
    else
    'text-muted'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/films/index.html.erb
<div class="container">
  <div class="container_wrap">
    <%= render 'shared/header' %>
    <div class="content">
      <div class="box_1">
      	<h1 class="m_2">Films</h1>
      </div>
      <%= form_tag films_path, :method => "get", :class =>'searchs' do %>
        <%= text_field_tag :search, params[:search], :placeholder => 'поиск', :class => 'inputs' %>
        <%= submit_tag "", :class => 'submits' %>
      <% end %>
      <div class="row">
	  		<div class="clearfix"> </div>
			  <% @films.each do |film| %>
				  <div class="col-md-8", id="block">
				    <br>
				    <ul class = "menu_uls">
				      <li class ="menu_lisa"><h4 class="lin"><%= link_to film.name, film %></h4></li>
				      <li class ="menu_liss"><%= link_to 'Show', edit_admin_film_path(film),class: "lin" %></li>
				    </ul>
				    <div class="row">
					    <div class="col-md-5">
					    <br>
						    <% if film.imagefilm_stored? %>
						      <%= image_tag film.imagefilm.url, height: 200 %>
						    <% else %>
						      <%= image_tag 'no_image.png', height: 200 %>
						    <% end %>	
					    </div>
					    <div class="col-md-6">
					    	<br>
						    <h6><b>Качество: </b> <%= film.quality %></h6>
						    <h6><b>Жанр: </b> <%= film.genre %></h6>
						    <h6><b>Дата выхода: </b> <%= film.year %></h6>
						    <h6><b>Страна: </b> <%= film.country %></h6>
						    <h6><b>Продолжительность: </b> <%= film.duration %></h6>
						    <h6><b>Продюсер: </b> <%= film.producer %></h6>
						    <h6><b>Премьера: </b><%= film.premiere %></h6>
						    <h6><b>Перевод: </b> <%= film.transfer %></h6>
						    <h6><b>Category:
						    <% film.categories.each do |category| %>
						      <%= category.name %>
						    <% end %></b></h6>
						    <h6><b>Описание: </b> <%= film.description %></h6>
						    <div class = "text_like">
                <% if current_user %>
                  <%= link_to like_film_path(film), method: :put do %>
                    <span><i class="fa fa-thumbs-up" aria-hidden="true"></i></span>
                    <%= film.get_upvotes.size %>
                  <% end %>
                  <%= link_to dislike_film_path(film), method: :put do %>
                    <span><i class="fa fa-thumbs-down" aria-hidden="true"></i></i></span>
                    <%= film.get_downvotes.size %>
                  <% end %>
                <% end %>
              </div>
					    </div>
					  </div>
				  </div>
			  <% end %>
			</div>
			<center><%= will_paginate @collection, renderer: BootstrapPagination::Rails %></center>
    </div>
  </div>
</div>
<div class = "container">
  <%= render 'shared/footer' %>
</div>

app/views/films/show.html.erb
<div class="container">
  <div class="container_wrap">
    <%= render 'shared/header' %>
    <div class="content">
      <div class="box_1">
      </div>
      <div class="row">
        <div class="clearfix"> </div>
          <div class="col-md-8", id="block">
            <br>
            <ul class = "menu_uls">
              <li class ="menu_lisa"><h4 class="lin"><%= @film.name %></h4></li>
            </ul>
            <div class="row">
              <div class="col-md-5">
              <br>
                <% if @film.imagefilm_stored? %>
                  <%= image_tag @film.imagefilm.url, height: 200 %>
                <% else %>
                  <%= image_tag 'no_image.png', height: 200 %>
                <% end %> 
              </div>
              <div class="col-md-7">
                <br>
                <h6><b>Качаство: </b> <%= @film.quality %></h6>
                <h6><b>Жанр: </b> <%= @film.genre %></h6>
                <h6><b>Дата выхода: </b> <%= @film.year %></h6>
                <h6><b>Страна: </b> <%= @film.country %></h6>
                <h6><b>Продолжительность: </b> <%= @film.duration %></h6>
                <h6><b>Продюсер: </b> <%= @film.producer %></h6>
                <h6><b>Премьера: </b><%= @film.premiere %></h6>
                <h6><b>Перевод: </b> <%= @film.transfer %></h6>
                <h6><b>Category:
                <% @film.categories.each do |category| %>
                  <%= category.name %>
                <% end %></b></h6>
                <h6><b>Описание: </b> <%= @film.description %></h6>
                <h6><b>Трейлер</b></h6>
                <h6><%= @film.treilerlink.html_safe  %></h6>
                <h6><b>Фильм</b></h6>
                <h6><%= @film.link.html_safe  %></h6>
              </div>
            </div>
          </div>
      </div>
      <h2, id="block">Comments</h2>
      <% @film.comments.each do |comment| %>
        <div class="row">
          <div class="col-md-8", id="block">
            <div class="panel panel-default">
              <div class="panel-heading">
                <strong><%= comment.commenter %></strong> <span class="text-muted"><%= time_ago_in_words(comment.created_at) %> Ago</span>
                <% if current_user.id == comment.user_id %>
                  <%= link_to 'Delete',  [comment.film, comment], method: :delete, class: 'label label-danger', data: { confirm: 'Are you sure'}%>
                <% else %>
                <% end %>
              </div>
              <div class="panel-body">
                <%= comment.body %>
              </div><!-- /panel-body -->
            </div><!-- /panel panel-default -->
          </div><!-- /col-sm-5 -->
        </div>
      <% end %>
      <%= form_for([@film, @film.comments.build]) do |f| %>
      <div id="block">
        <p>
          <%= f.label :commenter %><br />
          <%= f.text_field :commenter,class: 'form-control' %>
        </p>
        <p>
          <%= f.label :body %><br />
          <%= f.text_area :body,class: 'form-control'  %>
        </p>
        <br>
        <p>
          <%= f.submit "Create comments", class: 'btn btn-success' %>
        </p>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class = "container">
  <%= render 'shared/footer' %>
</div>