config/routes.rb
Rails.application.routes.draw do
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'log_in', to: 'sessions#new', as: 'log_in' 
  get 'sign_up' , to: 'users#new', as: 'sign_up'
 
  resources :users do
    get :change_permission, on: :member
  end
  
  resources :sessions
  get 'users/new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  get 'auth/vkontakte/callback', to: 'omniauth#create'
  get 'auth/facebook/callback', to: 'omniauth#create'

  namespace :admin do
    root 'users#index'
    resources :users, only: [:index, :destroy]
    resources :videos
    resources :films
    resources :cartoons
  end

  resources :videos do
     member do
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
    end
    get :favourite, on: :member
    get '/videos', to: 'pages#video'
  end

  resources :films do
    resources :comments
    member do
      put "like", to: "films#upvote"
      put "dislike", to: "films#downvote"
    end
    get '/films', to: 'pages#film'
  end

  resources :cartoons do
    member do
      put "like", to: "cartoons#upvote"
      put "dislike", to: "cartoons#downvote"
    end
    get '/cartoons', to: 'pages#cartoon'
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartoon.rb
class Cartoon < ApplicationRecord
	belongs_to :user
  acts_as_votable
	self.per_page = 4
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :films
	has_many :films
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :film
end

app/models/favourite_video.rb
class FavouriteVideo < ApplicationRecord
  belongs_to :user
  belongs_to :video

  def self.manage(video)
    object = find_by(video: video)
    object ? object.destroy : create(video: video)
  end
end

app/models/film.rb
class Film < ApplicationRecord
  dragonfly_accessor :imagefilm
  dragonfly_accessor :screenshotsactors
  has_and_belongs_to_many :categories
  belongs_to :category

  acts_as_votable
  has_many :comments

  self.per_page = 5
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  attr_accessor :password
  before_save :encrypt_password
  has_many :account, dependent: :destroy
  has_many :favourite_videos

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  acts_as_votable
  has_many :favourite_videos

  self.per_page = 4

	

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminsController
  before_action :authorize, only: [:index, :destroy]
  before_action :require_admin, only: [:index, :destroy]

  def index
    @users = User.all 
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  private

  def require_admin
    redirect_to root_path unless current_user.try(:admin?)
    flash[:success] = "You admin?"
  end
end

app/controllers/admins_controller.rb
class AdminsController < ActionController::Base
  layout 'admin/application'

  before_action :require_admin

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def authorize
    redirect_to log_in_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/cartoons_controller.rb
class CartoonsController < ApplicationController
    
  def index
    @cartoons = Cartoon.all.page(params[:page]).where("name LIKE ?", "%#{params[:search]}%") 
  end

  def upvote 
    @cartoon = Cartoon.find(params[:id])
    @cartoon.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @cartoon = Cartoon.find(params[:id])
    @cartoon.downvote_by current_user
    redirect_to :back
  end

  private


  def cartoon_params
    params.require(:cartoon).permit(:name)
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
	def index
    @films = Film.all.page(params[:page]).where("name LIKE ?", "%#{params[:search]}%")
  end

  def show
  	@film = Film.find(params[:id])
  end

  def upvote 
    @film = Film.find(params[:id])
    @film.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @film = Film.find(params[:id])
    @film.downvote_by current_user
    redirect_to :back
  end

  private

  def film_params 
    params.require(:film).permit(:name, :quality, :genre, :year, :country, :duration, :producer, :premiere, :transfer, :image_film, :description, :screenshots_and_actors, :link, :treilerlink, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_resourse, only: [:show, :edit, :update, :change_permission]

  def index
    @users = User.all
  end
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def change_permission
    @user.update(admin: !@user.admin)
    redirect_to :back
  end


  private
 
    def current_resourse
      @user = User.find(params[:id])
    end

    def set_user
      @user = current_user
    end
    
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :avatar)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :current_video, only: [:favourite]
    
  def index
    @videos = Video.all.page(params[:page]).where("name LIKE ?", "%#{params[:search]}%")
    
  end

  def favourite
    current_user.favourite_videos.manage(@video)
  end

  def upvote 
    @video = Video.find(params[:id])
    @video.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @video = Video.find(params[:id])
    @video.downvote_by current_user
    redirect_to :back
  end

  private

  def current_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:name)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartoons_helper.rb
module CartoonsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper

  def favourite_video(video)
    if current_user && current_user.favourite_videos.map(&:video).include?(video)
    'text-danger'
    else
    'text-muted'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/destroy.js.erb
$('#user_<%= @user.id %>').remove();

app/views/admin/users/index.html.erb
<div id="page_wrapper">
  <b><center>All Users</center></b>
  <br>
    <table class="table table-bordered">
      <tr>
        <td>№</td>
        <td class = "td_name">User</td>
        <td class = "td_name">Email</td>
        <td class = "td_name">Avatar</td>
        <td class = "td_name">Delete_user</td>
        <td class = "td_name">Make</td>
      </tr>
      <% @users.each do |user| %>
        <tr id = <%= "user_#{user.id}"%>>
          <td><%=user.id%></td>
          <td class = "td_name"><%=link_to user.firstname + " " + user.lastname, user %></td>
          <td class = "td_name"><%=user.email%></td>
          <td class = "td_name"><%=image_tag user.avatar.url(:avat), class: "img-circle"%></td>
          <td class = "td_name"><%= link_to 'Delete', admin_user_path(user),class: " label label-danger", method: :delete, remote: true, data: { confirm: 'Are you sure' } %></td>
          <td class = "td_name">
            <% if user.admin %>
            <%= link_to 'User', change_permission_user_path(user), class: "label label-primary"%>
            <% else %>
            <%= link_to 'Admin', change_permission_user_path(user), class: "label label-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="container_wrap">
  <%= render 'shared/header' %>
  <div class="content">
    <div class="register">
      <div class="register-top-grid">
          <h3>Personal Information</h3>
          <%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <h2>Form is invalid</h2>
            <ul>
              <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        <div>
          <%= f.label :Name %><br />
          <%= f.text_field :firstname %>
        </div>
        <div>
          <%= f.label :Last_name %><br />
          <%= f.text_field :lastname %>
        </div>
        <div>
          <%= f.label :email %><br />
          <%= f.text_field :email %>
        </div>
        <div>
          <%= f.label :Avatar %><br />
          <%= f.file_field :avatar, type: "file", class: "filestyle" , :input => false %>
        </div>
        <div class="clearfix"> </div>
          <a class="news-letter" href="#">
            <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i> </i>Sign Up for Newsletter</label>
          </a>
        </div>
        <div class="register-bottom-grid">
          <h3>Login Information</h3>
          <div>
            <%= f.label :password %><br />
            <%= f.text_field :password %>
          </div>
          <div>
            <%= f.label :password_confirmation %><br />
            <%= f.text_field :password_confirmation %>
          </div>
          <div class="clearfix"> </div>
        </div>
        <div class="clearfix"> </div>
        <div class="register-but">
          <%= f.submit "Update information", class: 'btn btn-success' %>
          <div class="clearfix"> </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container"> 
  <%= render 'shared/footer' %>
</div>

app/views/users/index.html.erb
<b><center>All Users</center></b>
<br>
<table class="table table-bordered">
  <tr>
    <td>№</td>
    <td>User</td>
    <td>Email</td>
  </tr>
  <% @users.each do |user| %>
      <tr>
        <td><%=user.id%></td>
        <td><%=link_to user.firstname + " " + user.lastname, user %></td>
        <td><%=user.email%></td>
      </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<div class="container">
  <div class="container_wrap">
  <%= render 'shared/header' %>
  <div class="content">
    <div class="register">
      <div class="register-top-grid">
          <h3>Personal Information</h3>
          <%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <h2>Form is invalid</h2>
            <ul>
              <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        <div>
          <%= f.label :Name %><br />
          <%= f.text_field :firstname %>
        </div>
        <div>
          <%= f.label :Last_name %><br />
          <%= f.text_field :lastname %>
        </div>
        <div>
          <%= f.label :email %><br />
          <%= f.text_field :email %>
        </div>
        <div>
          <%= f.label :Avatar %><br />
          <%= f.file_field :avatar, type: "file", class: "filestyle" , :input => false %>
        </div>
        <div class="clearfix"> </div>
          <a class="news-letter" href="#">
            <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i> </i>Sign Up for Newsletter</label>
          </a>
        </div>
        <div class="register-bottom-grid">
          <h3>Login Information</h3>
          <div>
            <%= f.label :password %><br />
            <%= f.text_field :password %>
          </div>
          <div>
            <%= f.label :password_confirmation %><br />
            <%= f.text_field :password_confirmation %>
          </div>
          <div class="clearfix"> </div>
        </div>
        <div class="clearfix"> </div>
        <div class="register-but">
          <%= f.submit "Create Account", class: 'btn btn-success' %>
          <div class="clearfix"> </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container"> 
  <%= render 'shared/footer' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="container_wrap">
    <%= render 'shared/header' %>
    <div class="content">
      <h3><center>My Account</center></h3>
      <br>
      <center>
        <p>
          <%= image_tag current_user.avatar_url(:medium ), class: "img-circles" %>
        </p>
        <br>
        <p> 
          <h4>
          <%= @user.firstname %>
          <%= @user.lastname %>
          </h4>
        </p>
        <p>
          <i class="glyphicon glyphicon-envelope"></i> <%= @user.email %>
        </p>
        <div class="clearfix"> </div>
        <br>
          <button type="buttonss" class="btn btn-primary"><%= link_to 'Edit_user', edit_user_path(@user), class: 'buttonss' %></button>
      </center>
    </div>
  </div>
</div>
<div class="container"> 
  <%= render 'shared/footer' %>
</div>