config/routes.rb
Rails.application.routes.draw do
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'log_in', to: 'sessions#new', as: 'log_in' 
  get 'sign_up' , to: 'users#new', as: 'sign_up'
 
  resources :users do
    get :change_permission, on: :member
  end
  
  resources :sessions
  get 'users/new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  get 'auth/vkontakte/callback', to: 'omniauth#create'
  get 'auth/facebook/callback', to: 'omniauth#create'

  namespace :admin do
    root 'users#index'
    resources :users, only: [:index, :destroy]
    resources :videos
    resources :films
    resources :cartoons
  end

  resources :videos do
     member do
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
    end
    get :favourite, on: :member
    get '/videos', to: 'pages#video'
  end

  resources :films do
    resources :comments
    member do
      put "like", to: "films#upvote"
      put "dislike", to: "films#downvote"
    end
    get '/films', to: 'pages#film'
  end

  resources :cartoons do
    member do
      put "like", to: "cartoons#upvote"
      put "dislike", to: "cartoons#downvote"
    end
    get '/cartoons', to: 'pages#cartoon'
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartoon.rb
class Cartoon < ApplicationRecord
	belongs_to :user
  acts_as_votable
	self.per_page = 4
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :films
	has_many :films
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :film
end

app/models/favourite_video.rb
class FavouriteVideo < ApplicationRecord
  belongs_to :user
  belongs_to :video

  def self.manage(video)
    object = find_by(video: video)
    object ? object.destroy : create(video: video)
  end
end

app/models/film.rb
class Film < ApplicationRecord
  dragonfly_accessor :imagefilm
  dragonfly_accessor :screenshotsactors
  has_and_belongs_to_many :categories
  belongs_to :category

  acts_as_votable
  has_many :comments

  self.per_page = 5
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  attr_accessor :password
  before_save :encrypt_password
  has_many :account, dependent: :destroy
  has_many :favourite_videos

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  acts_as_votable
  has_many :favourite_videos

  self.per_page = 4

	

end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminsController
  before_action :authorize, only: [:index, :destroy, :new]
  before_action :require_admin, only: [:index, :destroy, :new]
  before_action :current_video, only: [:show, :edit, :update, :destroy]


  def index
    @videos = Video.all.where("name LIKE ?", "%#{params[:search]}%")
  end

  def new
    @video = Video.new
  end

  def create
    
  end

  def create
      @video = Video.create(video_params)
    if @video.save
      redirect_to admin_videos_path 
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @video.update(video_params)
      redirect_to admin_videos_path 
    else
      render 'edit'
    end
  end

  def destroy
    @video.destroy
    redirect_to admin_videos_path 
  end


  private

  def video_params 
    params.require(:video).permit(:name, :link)
  end

  def current_video
    @video = Video.find(params[:id])
  end

  def require_admin
    redirect_to root_path unless current_user.try(:admin?)
    flash[:success] = "You admin?"
  end
end

app/controllers/admins_controller.rb
class AdminsController < ActionController::Base
  layout 'admin/application'

  before_action :require_admin

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def authorize
    redirect_to log_in_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/cartoons_controller.rb
class CartoonsController < ApplicationController
    
  def index
    @cartoons = Cartoon.all.page(params[:page]).where("name LIKE ?", "%#{params[:search]}%") 
  end

  def upvote 
    @cartoon = Cartoon.find(params[:id])
    @cartoon.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @cartoon = Cartoon.find(params[:id])
    @cartoon.downvote_by current_user
    redirect_to :back
  end

  private


  def cartoon_params
    params.require(:cartoon).permit(:name)
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
	def index
    @films = Film.all.page(params[:page]).where("name LIKE ?", "%#{params[:search]}%")
  end

  def show
  	@film = Film.find(params[:id])
  end

  def upvote 
    @film = Film.find(params[:id])
    @film.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @film = Film.find(params[:id])
    @film.downvote_by current_user
    redirect_to :back
  end

  private

  def film_params 
    params.require(:film).permit(:name, :quality, :genre, :year, :country, :duration, :producer, :premiere, :transfer, :image_film, :description, :screenshots_and_actors, :link, :treilerlink, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_resourse, only: [:show, :edit, :update, :change_permission]

  def index
    @users = User.all
  end
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def change_permission
    @user.update(admin: !@user.admin)
    redirect_to :back
  end


  private
 
    def current_resourse
      @user = User.find(params[:id])
    end

    def set_user
      @user = current_user
    end
    
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :avatar)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :current_video, only: [:favourite]
    
  def index
    @videos = Video.all.page(params[:page]).where("name LIKE ?", "%#{params[:search]}%")
    
  end

  def favourite
    current_user.favourite_videos.manage(@video)
  end

  def upvote 
    @video = Video.find(params[:id])
    @video.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @video = Video.find(params[:id])
    @video.downvote_by current_user
    redirect_to :back
  end

  private

  def current_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:name)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartoons_helper.rb
module CartoonsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper

  def favourite_video(video)
    if current_user && current_user.favourite_videos.map(&:video).include?(video)
    'text-danger'
    else
    'text-muted'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/videos/destroy.js.erb
$('#user_<%= @user.id %>').remove();

app/views/admin/videos/edit.html.erb
<h1 >Edit Videos</h1>
<%= form_for [:admin, @video] do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </p>
  <p>
    <%= f.label :link %><br>
    <%= f.text_field :link, class: "form-control", value: '<iframe width="100%" height="305"' %>
  </p>
  <br>
  <p>
    <%= f.submit class: 'btn btn-success' %>
  </p>
<% end %>

app/views/admin/videos/index.html.erb
<center><h2>List Videos</h2></center>
<%= link_to new_admin_video_path, class: "linkss" do %>Add Video <%= image_tag "add-video.png" %><% end %>
<%= form_tag admin_videos_path, :method => "get", :class =>'search' do %>
  <%= text_field_tag :search, params[:search], :placeholder => 'поиск', :class => 'input' %>
  <%= submit_tag "", :class => 'submit' %>
<% end %>
<div class="row">
  <div class="clearfix"> </div>
  <% @videos.each do |video| %>
    <div class="col-md-6">
    <br>
    <ul class = "menu_uls">
      <li class ="menu_lisa"><h4 class="lin"><%= video.name%></h4></li>
      <li class ="menu_lissa"><%= link_to 'Delete', admin_video_path(video),class: " lin", method: :delete, data: { confirm: 'Are you sure' } %></li>
      <li class ="menu_lissa"><%= link_to 'Edit', edit_admin_video_path(video),class: "lin" %></li>
    </ul>
      <h4><%= video.link.html_safe  %></h4>
    </div>
  <% end %>
</div>

app/views/admin/videos/new.html.erb
<h1 >Add Videos</h1>
<%= form_for [:admin, @video] do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </p>
  <p>
    <%= f.label :link %><br>
    <%= f.text_field :link, class: "form-control", value: '<iframe width="100%" height="305"' %>
  </p>
  <br>
  <p>
    <%= f.submit class: 'btn btn-success' %>
  </p>
<% end %>

app/views/videos/favourite.js.erb
$('#video_<%= @video.id %>').toggleClass('text-danger').toggleClass('text-muted');

app/views/videos/index.html.erb
<div class="container">
  <div class="container_wrap">
    <%= render 'shared/header' %>
    <div class="content">
      <div class="box_1">
      <h1 class="m_2">Videos</h1>
      <%= form_tag videos_path, :method => "get", :class =>'search' do %>
        <%= text_field_tag :search, params[:search], :placeholder => 'поиск', :class => 'input' %>
        <%= submit_tag "", :class => 'submit' %>
      <% end %>
        <div class="row">
          <div class="clearfix"> </div>
          <% @videos.each do |video| %>
            <div class="col-md-6">
              <ul class = "menu_uls">
                <li class ="menu_lisa"><h4 class="lin"><%= video.name%></h4></li>
              </ul>
              <h4><%= video.link.html_safe  %></h4>
              <div class = "text_like">
                <% if current_user %>
                  <%= link_to like_video_path(video), method: :put do %>
                    <span><i class="fa fa-thumbs-up" aria-hidden="true"></i></span>
                    <%= video.get_upvotes.size %>
                  <% end %>
                  <%= link_to dislike_video_path(video), method: :put do %>
                    <span><i class="fa fa-thumbs-down" aria-hidden="true"></i></i></span>
                    <%= video.get_downvotes.size %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <center><%= will_paginate @collection, renderer: BootstrapPagination::Rails %></center>
    </div>
  </div>
</div>
<div class = "container">
  <%= render 'shared/footer' %>
</div>

app/views/videos/new.html.erb
<div class="container">
  <div class="container_wrap">
    <%= render 'shared/header' %>
    <div class="content">
      <div class="box_1">
        <h1 class="m_2">Add Videos</h1>
        <%= form_for @video do |f| %>
          <p>
            <%= f.label :name %><br>
            <%= f.text_field :name, class: "form-control" %>
          </p>
          <p>
            <%= f.label :link %><br>
            <%= f.text_field :link, class: "form-control", value: '<iframe width="100%" height="305"' %>
          </p>
          <br>
          <p>
            <%= f.submit class: 'btn btn-success' %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class = "container">
  <%= render 'shared/footer' %>
</div>